import json
import os
import uuid
import datetime
import click
from rich.console import Console
from rich.panel import Panel
from perftrace.cli.db_utils import check_retrieve_data

console = Console()
RANDOM_ID = uuid.uuid4()

_HTML_CSS = """
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; background: #0f1117; color: #e2e8f0; margin: 0; padding: 24px; }
  h1 { color: #63b3ed; font-size: 1.8rem; margin-bottom: 4px; }
  .meta { color: #718096; font-size: 0.85rem; margin-bottom: 24px; }
  .badge { display: inline-block; background: #2d3748; border-radius: 12px; padding: 2px 10px;
           font-size: 0.78rem; color: #90cdf4; margin-right: 6px; }
  table { width: 100%; border-collapse: collapse; font-size: 0.82rem; }
  thead th { background: #1a202c; color: #63b3ed; text-align: left; padding: 10px 12px;
             border-bottom: 2px solid #2d3748; white-space: nowrap; }
  tbody tr:nth-child(even) { background: #171923; }
  tbody tr:nth-child(odd)  { background: #1a202c; }
  tbody tr:hover { background: #2d3748; }
  td { padding: 8px 12px; border-bottom: 1px solid #2d3748; vertical-align: top; word-break: break-word; }
  td.exc-yes { color: #fc8181; font-weight: bold; }
  td.exc-no  { color: #68d391; }
  .footer { margin-top: 24px; color: #4a5568; font-size: 0.75rem; }
</style>
"""


def _json_cell(value):
    """Render a cell value: expand JSON dicts as key: value lines."""
    if value is None or str(value).strip() in ("", "nan", "None"):
        return "<span style='color:#4a5568'>—</span>"
    if isinstance(value, str):
        try:
            value = json.loads(value)
        except Exception:
            return str(value)
    if isinstance(value, dict):
        return "<br>".join(
            f"<span style='color:#90cdf4'>{k}</span>: {v}" for k, v in value.items()
        )
    return str(value)


def _exception_cell(value):
    """Render exception_collector column with colour coding."""
    if value is None or str(value).strip() in ("", "nan", "None"):
        return "<td class='exc-no'>—</td>"
    if isinstance(value, str):
        try:
            value = json.loads(value)
        except Exception:
            return f"<td>{value}</td>"
    if isinstance(value, dict):
        if value.get("occurred"):
            exc_type = value.get("exception_type", "Unknown")
            exc_msg = value.get("exception_message", "")
            tb = (value.get("traceback") or "").strip().replace("\n", "<br>")
            return (
                f"<td class='exc-yes'>{exc_type}: {exc_msg}"
                f"<details><summary style='cursor:pointer;color:#fc8181'>traceback</summary>"
                f"<pre style='color:#fc8181;font-size:0.75rem;white-space:pre-wrap'>{tb}</pre>"
                f"</details></td>"
            )
        return "<td class='exc-no'>None</td>"
    return f"<td>{value}</td>"


def _build_html(df, title, label):
    generated = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    rows_html = []
    for _, row in df.iterrows():
        cells = []
        for col in df.columns:
            val = row[col]
            if col == "exception_collector":
                cells.append(_exception_cell(val))
            else:
                cells.append(f"<td>{_json_cell(val)}</td>")
        rows_html.append(f"<tr>{''.join(cells)}</tr>")

    headers = "".join(f"<th>{c}</th>" for c in df.columns)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
{_HTML_CSS}
</head>
<body>
<h1>PerfTrace — {label}</h1>
<p class="meta">
  <span class="badge">Generated: {generated}</span>
  <span class="badge">Rows: {len(df)}</span>
</p>
<table>
  <thead><tr>{headers}</tr></thead>
  <tbody>{''.join(rows_html)}</tbody>
</table>
<p class="footer">Generated by <strong>PerfTrace</strong> · perftrace.cli</p>
</body>
</html>"""


def _export_html(df, filename, label):
    if not filename.endswith(".html"):
        filename += ".html"

    if df.empty:
        console.print(f"[yellow]No {label} data found to export.[/yellow]")
        return

    html = _build_html(df, f"PerfTrace {label} Report", label)
    with open(filename, "w", encoding="utf-8") as f:
        f.write(html)

    abs_path = os.path.abspath(filename)
    size_kb = os.path.getsize(abs_path) / 1024
    console.print(Panel.fit(
        f"[bold green]HTML export successful[/bold green]\n"
        f"[cyan]File:[/cyan]  {abs_path}\n"
        f"[cyan]Rows:[/cyan]  {len(df)}\n"
        f"[cyan]Size:[/cyan]  {size_kb:.1f} KB",
        title=f"[bold]{label} HTML Export[/bold]",
        border_style="green"
    ))


@click.command(name="export-html")
@click.option("--filename", default=f"perftrace_all_{RANDOM_ID}.html", help="Output HTML filename")
def export_all_html(filename):
    """Export complete PerfTrace database to HTML."""
    try:
        df = check_retrieve_data()
        _export_html(df, filename, "All Data")
    except Exception as e:
        console.print(f"[bold red]Export failed:[/bold red] {e}")


@click.command(name="export-function-html")
@click.option("--filename", default=f"perftrace_function_{RANDOM_ID}.html", help="Output HTML filename")
def export_function_html(filename):
    """Export function trace records to HTML."""
    try:
        df = check_retrieve_data()
        df = df.dropna(subset=["function_name"])
        if "context_tag" in df.columns:
            df = df.drop(columns=["context_tag"])
        _export_html(df, filename, "Function")
    except Exception as e:
        console.print(f"[bold red]Export failed:[/bold red] {e}")


@click.command(name="export-context-html")
@click.option("--filename", default=f"perftrace_context_{RANDOM_ID}.html", help="Output HTML filename")
def export_context_html(filename):
    """Export context manager trace records to HTML."""
    try:
        df = check_retrieve_data()
        df = df.dropna(subset=["context_tag"])
        if "function_name" in df.columns:
            df = df.drop(columns=["function_name"])
        _export_html(df, filename, "Context")
    except Exception as e:
        console.print(f"[bold red]Export failed:[/bold red] {e}")
